import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Banner from "../components/Banner";
import Card from "../components/Card";
import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData
    },
  };
}

export default function Home({ coffeeStores }) {
  const handleBannerButtonClick = () => {
    console.log("hi");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonTitle="view stores nearby"
          buttonClick={handleBannerButtonClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/heroImage.png" width={200} height={200} />
        </div>
        {coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Totonto Stores</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((cs) => (
                <Card
                  name={cs.name}
                  href={`/CoffeeStores/${cs.id}`}
                  key={cs.Id}
                  imageUrl={cs.imgUrl}
                  className={styles.card}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
