import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";

export default function Home() {
  const handleBannerButtonClick = () => {
    console.log("hi");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonTitle="view stores nearby"
          buttonClick={handleBannerButtonClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/heroImage.png" width={200} height={200} />
        </div>
      </main>
    </div>
  );
}
